apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snapstudy

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - migration-job.yaml
  - web-deployment.yaml
  - api-gateway-deployment.yaml
  - notes-service-deployment.yaml
  - progress-service-deployment.yaml
  - services.yaml
