apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-service
  template:
    metadata:
      labels:
        app: progress-service
    spec:
      containers:
        - name: progress-service
          image: snapstudyacr.azurecr.io/progress-service:latest
          ports:
            - containerPort: 4002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: snapstudy-secrets
