apiVersion: v1
kind: Secret
metadata:
  name: snapstudy-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://snapstudy:snapstudy@postgres:5432/snapstudy"
  JWT_SECRET: "snapstudy-k8s-jwt-secret-change-in-production"
  NOTES_SERVICE_URL: "http://notes-service:4001"
  PROGRESS_SERVICE_URL: "http://progress-service:4002"
  AZURE_STORAGE_CONNECTION_STRING: ""
  AZURE_STORAGE_CONTAINER_NAME: "photo-notes"
  AZURE_FORM_RECOGNIZER_ENDPOINT: ""
  AZURE_FORM_RECOGNIZER_KEY: ""
